"""Fix Image's post_id field nullable

Revision ID: 9afa1693ecb6
Revises: c89ccb4507b0
Create Date: 2023-11-06 19:35:07.120775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9afa1693ecb6'
down_revision: Union[str, None] = 'c89ccb4507b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'post_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'post_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
