"""Define Verifiction Code Model

Revision ID: f0a6a34a3a99
Revises: 06038909f041
Create Date: 2023-10-14 15:20:51.363496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.guid

# revision identifiers, used by Alembic.
revision: str = 'f0a6a34a3a99'
down_revision: Union[str, None] = '06038909f041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code'))
    )
    op.create_index(op.f('ix_code_email'), 'code', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_email'), table_name='code')
    op.drop_table('code')
    # ### end Alembic commands ###
