"""Add relationship between Post and Image

Revision ID: c89ccb4507b0
Revises: 89ad51f0dce9
Create Date: 2023-11-06 18:03:38.839567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.guid

# revision identifiers, used by Alembic.
revision: str = 'c89ccb4507b0'
down_revision: Union[str, None] = '89ad51f0dce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('post_id', app.models.guid.GUID(), nullable=False))
    op.create_index(op.f('ix_image_post_id'), 'image', ['post_id'], unique=False)
    op.create_foreign_key(op.f('fk_image_post_id_post'), 'image', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_image_post_id_post'), 'image', type_='foreignkey')
    op.drop_index(op.f('ix_image_post_id'), table_name='image')
    op.drop_column('image', 'post_id')
    # ### end Alembic commands ###
