"""Add Notification Model

Revision ID: bbfbaad7c645
Revises: 624fe5447f47
Create Date: 2023-11-14 20:02:20.756776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.guid

# revision identifiers, used by Alembic.
revision: str = 'bbfbaad7c645'
down_revision: Union[str, None] = '624fe5447f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('sender_id', app.models.guid.GUID(), nullable=False),
    sa.Column('recipient_id', app.models.guid.GUID(), nullable=False),
    sa.Column('post_id', app.models.guid.GUID(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_notification_post_id_post'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], name=op.f('fk_notification_recipient_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('fk_notification_sender_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
