"""Define Post Related Models

Revision ID: 991218a13c8f
Revises: f0a6a34a3a99
Create Date: 2023-10-14 19:25:06.045445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.guid


# revision identifiers, used by Alembic.
revision: str = '991218a13c8f'
down_revision: Union[str, None] = 'f0a6a34a3a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('user_id', app.models.guid.GUID(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('post_image_url', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_post_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post')),
    sa.UniqueConstraint('user_id', name=op.f('uq_post_user_id'))
    )
    op.create_table('comment',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('post_id', app.models.guid.GUID(), nullable=False),
    sa.Column('user_id', app.models.guid.GUID(), nullable=False),
    sa.Column('content', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_comment_post_id_post')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_comment_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment')),
    sa.UniqueConstraint('post_id', name=op.f('uq_comment_post_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_comment_user_id'))
    )
    op.create_table('post_like',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('post_id', app.models.guid.GUID(), nullable=False),
    sa.Column('user_id', app.models.guid.GUID(), nullable=False),
    sa.Column('is_liked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_post_like_post_id_post')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_post_like_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_like')),
    sa.UniqueConstraint('post_id', name=op.f('uq_post_like_post_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_post_like_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_like')
    op.drop_table('comment')
    op.drop_table('post')
    # ### end Alembic commands ###
