"""Updated Post Models

Revision ID: 18ad46387fbb
Revises: 991218a13c8f
Create Date: 2023-10-14 23:35:32.946690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ad46387fbb'
down_revision: Union[str, None] = '991218a13c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_post_user_id', 'post', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_post_user_id', 'post', ['user_id'])
    # ### end Alembic commands ###
