"""Add origin & mask field to Post

Revision ID: 624fe5447f47
Revises: 97ac0ba81da8
Create Date: 2023-11-13 15:37:21.752773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '624fe5447f47'
down_revision: Union[str, None] = '97ac0ba81da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'origin_image',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('image', 'mask_image',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('post', sa.Column('origin_image_url', sa.TEXT(), nullable=True))
    op.add_column('post', sa.Column('mask_image_url', sa.TEXT(), nullable=True))
    op.alter_column('post', 'image_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'image_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('post', 'mask_image_url')
    op.drop_column('post', 'origin_image_url')
    op.alter_column('image', 'mask_image',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('image', 'origin_image',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
