"""Edited PostLike Model Detail

Revision ID: 68b90ca43141
Revises: dc55c6de3e8a
Create Date: 2023-10-15 02:06:05.070970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68b90ca43141'
down_revision: Union[str, None] = 'dc55c6de3e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_like', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False))
    op.add_column('post_like', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False))
    op.drop_constraint('uq_post_like_post_id', 'post_like', type_='unique')
    op.drop_constraint('uq_post_like_user_id', 'post_like', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_post_like_user_id', 'post_like', ['user_id'])
    op.create_unique_constraint('uq_post_like_post_id', 'post_like', ['post_id'])
    op.drop_column('post_like', 'updated_at')
    op.drop_column('post_like', 'created_at')
    # ### end Alembic commands ###
