"""Remove relationship between Image and Post

Revision ID: 1f58a95f8547
Revises: 89697afa66b5
Create Date: 2023-10-28 18:27:34.899802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f58a95f8547'
down_revision: Union[str, None] = '89697afa66b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_image_post_id', table_name='image')
    op.drop_constraint('uq_image_user_id', 'image', type_='unique')
    op.drop_constraint('fk_image_post_id_post', 'image', type_='foreignkey')
    op.drop_column('image', 'post_id')
    op.add_column('post', sa.Column('image_url', sa.TEXT(), nullable=False))
    op.drop_index('ix_post_image_id', table_name='post')
    op.drop_constraint('fk_post_image_id_image', 'post', type_='foreignkey')
    op.drop_column('post', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_post_image_id_image', 'post', 'image', ['image_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_post_image_id', 'post', ['image_id'], unique=False)
    op.drop_column('post', 'image_url')
    op.add_column('image', sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_image_post_id_post', 'image', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_image_user_id', 'image', ['user_id', 'post_id'])
    op.create_index('ix_image_post_id', 'image', ['post_id'], unique=False)
    # ### end Alembic commands ###
